### PR TITLE
Spring to Kube native workshop cleanup

### PR DESCRIPTION
**Pull request by edeandrea**
Mostly minor grammar edits & adding hyperlinks to other places.

### CODE REVIEW

**Comment by danieloh30** [comment]
I actually meant the service name, `customer` rather than the custom health check. Do you think that custom is better for readers to understand the context?

**Comment by edeandrea** [comment]
Yeah I figured you did mean the `customer` service name. IDK "custom health check" just sounded better to me, but not a big deal if you want me to change it back.

**Comment by danieloh30** [comment]
Ok. can you update the PR to rollback `customer`?

**Comment by edeandrea** [comment]
Done

**Pull request merged**
